---
title: Jakub Ptacnik
author: Jakub Ptacnik
email: jakub@jakubptacnik.com
description: 'Hi! I''m Jakub, a cyber security professional from Prague, Czech Republic. '
baseurl: ''
url: ''
defaults: []
plugins:
- jekyll-feed
- jekyll-menus
